# Generated by Django 4.2.8 on 2026-05-08 06:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('layer_type', models.CharField(choices=[('WATER', 'Water'), ('SEWERAGE', 'Sewerage'), ('ELECTRICITY', 'Electricity'), ('ROADS', 'Roads'), ('DRAINAGE', 'Drainage'), ('OTHER', 'Other')], db_index=True, max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(blank=True, null=True, srid=4326)),
                ('style', models.JSONField(blank=True, default=dict, help_text='Rendering style: {stroke_color, stroke_width, fill_color, opacity}')),
                ('source_file', models.CharField(blank=True, help_text='Original uploaded filename', max_length=255)),
                ('is_public', models.BooleanField(db_index=True, default=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='{source, last_verified, responsible_officer, notes}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'gis_customlayer',
                'ordering': ['layer_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LayerFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(blank=True, db_index=True, help_text='e.g. "WL-001"', max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('custom_layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='bda_gis.customlayer')),
            ],
            options={
                'db_table': 'gis_layerfeature',
            },
        ),
    ]
