# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonies', '0001_initial'),
        ('bda_gis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customlayer',
            name='colony',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gis_layers', to='colonies.colony'),
        ),
    ]
