# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bda_gis', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customlayer',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_layers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='layerfeature',
            index=models.Index(fields=['custom_layer'], name='gis_layerfe_custom__2af1e5_idx'),
        ),
    ]
