# Generated by Django 4.2.8 on 2026-05-12 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bda_gis', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasemapSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('url_template', models.CharField(help_text='Tile URL with {z}/{x}/{y} placeholders.', max_length=500)),
                ('attribution', models.CharField(blank=True, max_length=255)),
                ('max_zoom', models.PositiveSmallIntegerField(default=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_basemaps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gis_basemapsource',
                'ordering': ['name'],
            },
        ),
    ]
