# Generated by Django 4.2.8 on 2026-05-08 06:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colonies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_number', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], db_index=True, default='Residential', max_length=20)),
                ('area_sqy', models.DecimalField(blank=True, decimal_places=2, help_text='Area in square yards (from Excel)', max_digits=10, null=True)),
                ('area_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Area in sq m (auto-computed)', max_digits=10, null=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('allotted_lottery', 'Allotted – Lottery'), ('allotted_seniority', 'Allotted – Seniority'), ('ews', 'EWS'), ('patta_ok', 'Patta OK'), ('patta_missing', 'Patta Missing'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=30)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='colonies.colony')),
                ('primary_khasra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_plots', to='colonies.khasra')),
            ],
            options={
                'db_table': 'plots_plot',
                'ordering': ['colony', 'plot_number'],
            },
        ),
        migrations.CreateModel(
            name='PlotKhasraMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intersection_area_sqm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('khasra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_mappings', to='colonies.khasra')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khasra_mappings', to='plots.plot')),
            ],
            options={
                'db_table': 'plots_plotkhasramapping',
            },
        ),
    ]
