# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_plots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='plotkhasramapping',
            index=models.Index(fields=['plot'], name='plots_plotk_plot_id_17ac9b_idx'),
        ),
        migrations.AddIndex(
            model_name='plotkhasramapping',
            index=models.Index(fields=['khasra'], name='plots_plotk_khasra__400ed6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plotkhasramapping',
            unique_together={('plot', 'khasra')},
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['colony', 'status'], name='plots_plot_colony__a33565_idx'),
        ),
        migrations.AddIndex(
            model_name='plot',
            index=models.Index(fields=['colony', 'type'], name='plots_plot_colony__342bc2_idx'),
        ),
    ]
