# Generated by Django 4.2.8 on 2026-05-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plots', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plot',
            name='remarks',
            field=models.TextField(blank=True, help_text='Free-form internal notes about the plot.'),
        ),
    ]
