# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_filename', models.CharField(max_length=255)),
                ('file', models.FileField(help_text='Stored via DEFAULT_FILE_STORAGE (local or S3)', upload_to='documents/%Y/%m/')),
                ('file_size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('pdf', 'PDF'), ('jpg', 'JPEG'), ('png', 'PNG')], max_length=10)),
                ('mime_type', models.CharField(blank=True, max_length=60)),
                ('document_type', models.CharField(choices=[('patta', 'Patta'), ('survey', 'Survey'), ('mutation', 'Mutation'), ('amendment', 'Amendment'), ('other', 'Other')], db_index=True, default='patta', max_length=30)),
                ('dms_file_number', models.CharField(blank=True, db_index=True, help_text='DMS reference, e.g. BHR102703 (from Excel Col N)', max_length=20)),
                ('status', models.CharField(choices=[('uploaded', 'Uploaded'), ('verified', 'Verified'), ('linked', 'Linked')], db_index=True, default='uploaded', max_length=30)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'documents_document',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
