# Generated by Django 4.2.8 on 2026-05-08 06:18

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colony',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('zone', models.CharField(choices=[('North', 'North'), ('South', 'South'), ('East', 'East'), ('West', 'West'), ('Central', 'Central'), ('North-East', 'North-East'), ('South-East', 'South-East'), ('South-West', 'South-West')], default='Central', max_length=50)),
                ('chak_number', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('new', 'New'), ('archived', 'Archived')], default='active', max_length=20)),
                ('conversion_date', models.DateField(blank=True, null=True)),
                ('layout_approval_date', models.DateField(blank=True, null=True)),
                ('dlc_file_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('notified_area_bigha', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_residential_plots', models.IntegerField(default=0)),
                ('total_commercial_plots', models.IntegerField(default=0)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'colonies',
                'db_table': 'colonies_colony',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Khasra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('total_bigha', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('colony', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khasras', to='colonies.colony')),
            ],
            options={
                'db_table': 'colonies_khasra',
                'ordering': ['colony', 'number'],
            },
        ),
    ]
