# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('colonies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_colonies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='khasra',
            index=models.Index(fields=['colony'], name='colonies_kh_colony__5d1da8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='khasra',
            unique_together={('colony', 'number')},
        ),
        migrations.AddIndex(
            model_name='colony',
            index=models.Index(fields=['zone'], name='colonies_co_zone_ee2809_idx'),
        ),
        migrations.AddIndex(
            model_name='colony',
            index=models.Index(fields=['status'], name='colonies_co_status_e9a5fb_idx'),
        ),
    ]
