# Generated by Django 4.2.8 on 2026-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colony',
            options={'ordering': ['name'], 'verbose_name': 'Colony', 'verbose_name_plural': 'Colonies'},
        ),
        migrations.AlterModelOptions(
            name='khasra',
            options={'ordering': ['colony', 'number'], 'verbose_name': 'Khasra', 'verbose_name_plural': 'Khasras'},
        ),
        migrations.AddField(
            model_name='colony',
            name='colony_type',
            field=models.CharField(choices=[('bda_scheme', 'BDA Scheme'), ('private_approved', 'Private Approved Colony'), ('suo_moto', 'SUO-Moto Colony Case'), ('pending_layout', 'Pending Colony Layout'), ('rejected_layout', 'Rejected Colony Layout')], db_index=True, default='bda_scheme', help_text='Category shown on the public dashboard.', max_length=30),
        ),
        migrations.AddField(
            model_name='colony',
            name='layout_application_date',
            field=models.DateField(blank=True, help_text='Date on which the layout plan was submitted for approval.', null=True),
        ),
        migrations.AddField(
            model_name='colony',
            name='map_pdf',
            field=models.FileField(blank=True, help_text='Uploaded PDF copy of the colony layout plan.', null=True, upload_to='colony_maps/pdf/'),
        ),
        migrations.AddField(
            model_name='colony',
            name='map_png',
            field=models.FileField(blank=True, help_text='Uploaded PNG thumbnail of the colony layout plan.', null=True, upload_to='colony_maps/png/'),
        ),
        migrations.AddField(
            model_name='colony',
            name='map_svg',
            field=models.FileField(blank=True, help_text='Uploaded SVG version of the colony boundary map.', null=True, upload_to='colony_maps/svg/'),
        ),
        migrations.AddField(
            model_name='colony',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Populated only for rejected_layout colonies. Visible on public dashboard.'),
        ),
        migrations.AddField(
            model_name='colony',
            name='remarks',
            field=models.TextField(blank=True, help_text='Internal or public notes about this colony.'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='layout_approval_date',
            field=models.DateField(blank=True, help_text='Date on which the layout plan was formally approved.', null=True),
        ),
        migrations.AddIndex(
            model_name='colony',
            index=models.Index(fields=['colony_type'], name='colonies_co_colony__77398c_idx'),
        ),
    ]
