# Generated by Django 4.2.8 on 2026-05-11 10:09

from django.db import migrations, models


def remap_stale_zones(apps, schema_editor):
    """
    Existing rows may have legacy zones (North/South/Central/etc.).
    Coerce anything other than East or West to East — staff should
    reclassify these in the Django admin afterwards.
    """
    Colony = apps.get_model('colonies', 'Colony')
    Colony.objects.exclude(zone__in=['East', 'West']).update(zone='East')


def noop_reverse(apps, schema_editor):
    """No-op — original zones cannot be recovered."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0003_alter_colony_options_alter_khasra_options_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_stale_zones, noop_reverse),
        migrations.AlterField(
            model_name='colony',
            name='zone',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West')], default='East', max_length=20),
        ),
    ]
