# Generated by Django 4.2.8 on 2026-05-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0004_reduce_zones_to_east_west'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='boundary_file',
            field=models.FileField(blank=True, help_text='Source KML or shapefile (.kml/.zip) used to derive boundary geometry.', null=True, upload_to='colony_maps/boundary/'),
        ),
        migrations.AddField(
            model_name='colony',
            name='map_jpeg',
            field=models.FileField(blank=True, help_text='Uploaded JPEG of the colony layout plan.', null=True, upload_to='colony_maps/jpeg/'),
        ),
        migrations.AlterField(
            model_name='colony',
            name='colony_type',
            field=models.CharField(choices=[('bda_scheme', 'BDA Scheme'), ('private_approved', 'BDA Approved'), ('suo_moto', 'SUO-Moto'), ('pending_layout', 'Pending Layout Approval'), ('rejected_layout', 'Rejected Layout')], db_index=True, default='bda_scheme', help_text='Category shown on the public dashboard.', max_length=30),
        ),
        migrations.AlterField(
            model_name='colony',
            name='map_png',
            field=models.FileField(blank=True, help_text='Uploaded PNG of the colony layout plan.', null=True, upload_to='colony_maps/png/'),
        ),
    ]
