# Generated by Django 4.2.8 on 2026-05-11 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0005_add_map_jpeg_boundary_file_relabel_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='total_plots_per_layout',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
