# Generated by Django 4.2.8 on 2026-05-12 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colonies', '0006_add_total_plots_per_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='colony',
            name='revenue_village',
            field=models.CharField(blank=True, help_text='Source: Excel row 2 "ग्राम का नाम" (revenue village name).', max_length=200),
        ),
    ]
