# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patta_number', models.CharField(db_index=True, help_text='Plain integer from Excel, e.g. "3498"', max_length=50, unique=True)),
                ('allottee_name', models.CharField(db_index=True, max_length=255)),
                ('allottee_address', models.TextField(blank=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('amendment_date', models.DateField(blank=True, null=True)),
                ('challan_number', models.CharField(blank=True, max_length=50)),
                ('challan_date', models.DateField(blank=True, null=True)),
                ('lease_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lease_duration', models.CharField(blank=True, help_text='e.g. "10 वर्ष"', max_length=30)),
                ('regulation_file_present', models.BooleanField(blank=True, help_text='हाँ → True, नही → False, blank → None (not recorded)', null=True)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('missing', 'Missing'), ('cancelled', 'Cancelled'), ('amended', 'Amended'), ('superseded', 'Superseded')], db_index=True, default='issued', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pattas_patta',
                'ordering': ['colony', 'patta_number'],
            },
        ),
        migrations.CreateModel(
            name='PattaVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(help_text='Full serialized patta at this point in time')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pattas_pattaversion',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PlotPattaMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownership_share_pct', models.DecimalField(decimal_places=2, default=100.0, help_text='Share percentage this patta holds over this plot', max_digits=5)),
                ('allottee_role', models.CharField(blank=True, choices=[('owner', 'Owner'), ('co-owner', 'Co-Owner'), ('legatee', 'Legatee'), ('heir', 'Heir')], max_length=50)),
                ('document_status', models.CharField(blank=True, choices=[('issued', 'Issued'), ('missing', 'Missing'), ('verified', 'Verified')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plot_mappings', to='pattas.patta')),
            ],
            options={
                'db_table': 'pattas_plotpattamapping',
            },
        ),
    ]
