# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pattas', '0001_initial'),
        ('plots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plotpattamapping',
            name='plot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patta_mappings', to='plots.plot'),
        ),
    ]
