# Generated by Django 4.2.8 on 2026-05-08 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pattas', '0002_initial'),
        ('colonies', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pattaversion',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pattaversion',
            name='patta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='pattas.patta'),
        ),
        migrations.AddField(
            model_name='patta',
            name='colony',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pattas', to='colonies.colony'),
        ),
        migrations.AddField(
            model_name='patta',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patta_set', to='documents.document'),
        ),
        migrations.AddField(
            model_name='patta',
            name='superseded_by',
            field=models.ForeignKey(blank=True, help_text='If status=superseded, points to the replacement patta', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supersedes', to='pattas.patta'),
        ),
        migrations.AddField(
            model_name='patta',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pattas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='plotpattamapping',
            index=models.Index(fields=['plot'], name='pattas_plot_plot_id_ff5e9c_idx'),
        ),
        migrations.AddIndex(
            model_name='plotpattamapping',
            index=models.Index(fields=['patta'], name='pattas_plot_patta_i_2a41c4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='plotpattamapping',
            unique_together={('plot', 'patta')},
        ),
        migrations.AddIndex(
            model_name='patta',
            index=models.Index(fields=['colony', 'status'], name='pattas_patt_colony__5c24b1_idx'),
        ),
        migrations.AddIndex(
            model_name='patta',
            index=models.Index(fields=['allottee_name'], name='pattas_patt_allotte_60be8a_idx'),
        ),
    ]
